services:
  app:
    build: .
    volumes:
      - .:/app
      - static-data:/app/staticfiles
      - media-data:/app/media
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "440:440"  # Changed to standard HTTP port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static-data:/app/staticfiles
      - media-data:/app/media
    depends_on:
      - app
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network  # Added network
    healthcheck:   # Added healthcheck
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --pool=prefork --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
    environment:
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=redis://redis:6379/0  # Added broker URL
    networks:
      - app-network  # Added network

networks:
  app-network:
    driver: bridge

volumes:
  static-data:
  media-data:
  redis_data:  # Added missing volume
